---
version: "3.8"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=acanas23
      - MYSQL_DATABASE=swad
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mariadb:/config
    ports:
      - 3306:3306
    networks:
      - swad

  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      ports:
       - 8080:8978
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace
      networks:
       - swad
networks:
  swad:
    name: swad_it
    driver: bridge

volumes:
  cloudbeaver:
  mariadb:
