---
version: "3.8"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=acanas23
      - MYSQL_DATABASE=swad
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mariadb:/config
    ports:
      - 3306:3306
    networks:
      - swad

    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-pacanas23' ] 
      interval: 1s
      retries: 5

  cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      container_name: cloudbeaver
      ports:
       - 8080:8978
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace
      networks:
       - swad

  swad:
    build: .
    container_name: swad
    ports:
      - 5000:5000
    networks:
      - swad
    depends_on:
      mariadb:
        condition: service_healthy



networks:
  swad:
    name: swad_it
    driver: bridge

volumes:
  cloudbeaver:
  mariadb:
